version: "3.5"
services:
  mongodb:
    image: mongo:5.0.9
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - ${DOCKER_VOLUME}/mongodb/data:/data/db